import { EquipmentStatus } from "@prisma/client";

export type SeedEquipmentImage = {
  url: string;
  alt: string;
  sortOrder: number;
};

export type SeedEquipmentSpec = {
  name: string;
  value: string;
  unit?: string | null;
};

export type SeedEquipment = {
  categorySlug: string;
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  brand: string;
  model: string;
  dailyPrice: number;
  depositAmount: number;
  quantityTotal: number;
  baseQuantityAvailable: number;
  power: number | null;
  weight: number | null;
  status: EquipmentStatus;
  isFeatured: boolean;
  images: SeedEquipmentImage[];
  specs: SeedEquipmentSpec[];
};

type EquipmentFactoryInput = Omit<SeedEquipment, "images" | "specs"> & {
  imageUrls: string[];
  specs: SeedEquipmentSpec[];
};

function buildImages(name: string, imageUrls: string[]): SeedEquipmentImage[] {
  return imageUrls.map((url, index) => ({
    url,
    alt: `${name} view ${index + 1}`,
    sortOrder: index,
  }));
}

function equipment(input: EquipmentFactoryInput): SeedEquipment {
  return {
    ...input,
    images: buildImages(input.name, input.imageUrls),
  };
}

const imageLibrary = {
  demolition: [
    "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=1200&q=80",
  ],
  mixer: [
    "https://images.unsplash.com/photo-1599707254554-027aeb4deacd?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=80",
  ],
  compactor: [
    "https://images.unsplash.com/photo-1541976590-713941681591?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1597157639073-69284dc0fdaf?auto=format&fit=crop&w=1200&q=80",
  ],
  generator: [
    "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80",
  ],
  compressor: [
    "https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80",
  ],
  scaffolding: [
    "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80",
  ],
  welding: [
    "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=1200&q=80",
  ],
  saws: [
    "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80",
  ],
  measuring: [
    "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
  ],
} satisfies Record<string, string[]>;

export const EQUIPMENT_SEEDS: SeedEquipment[] = [
  equipment({
    categorySlug: "demolition-hammers",
    slug: "bosch-gbh-8-45dv",
    name: "Bosch GBH 8-45 DV Rotary Hammer",
    shortDescription: "Professional SDS-max hammer for drilling anchors and heavy chiseling.",
    description: "Reliable rotary hammer for facade crews, opening works, and reinforced concrete drilling on active building sites.",
    brand: "Bosch",
    model: "GBH 8-45 DV",
    dailyPrice: 45,
    depositAmount: 220,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 1.5,
    weight: 8.9,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Impact energy", value: "12.5", unit: "J" },
      { name: "Chuck type", value: "SDS-max" },
      { name: "Drilling diameter", value: "45", unit: "mm" },
      { name: "Operating mode", value: "Drilling and chiseling" },
    ],
  }),
  equipment({
    categorySlug: "demolition-hammers",
    slug: "makita-hm1214c",
    name: "Makita HM1214C Demolition Hammer",
    shortDescription: "Compact demolition hammer for wall chasing and tile removal.",
    description: "Balanced breaker for daily finishing crews that need solid impact power without oversized transport requirements.",
    brand: "Makita",
    model: "HM1214C",
    dailyPrice: 42,
    depositAmount: 210,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 1.5,
    weight: 12.3,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Impact energy", value: "19.9", unit: "J" },
      { name: "Vibration control", value: "AVT" },
      { name: "Voltage", value: "220", unit: "V" },
      { name: "Case included", value: "Yes" },
    ],
  }),
  equipment({
    categorySlug: "demolition-hammers",
    slug: "dewalt-d25902k",
    name: "DeWalt D25902K Breaker",
    shortDescription: "Heavy chipping hammer for slab removal and brick dismantling.",
    description: "A powerful breaker for demolition crews working on reinforced slabs, channels, and dense masonry walls.",
    brand: "DeWalt",
    model: "D25902K",
    dailyPrice: 48,
    depositAmount: 240,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 1.55,
    weight: 10.5,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Impact energy", value: "19", unit: "J" },
      { name: "Tool holder", value: "SDS-max" },
      { name: "Blows per minute", value: "2100" },
      { name: "Use case", value: "Slab and wall demolition" },
    ],
  }),
  equipment({
    categorySlug: "demolition-hammers",
    slug: "hilti-te-1000-avr",
    name: "Hilti TE 1000-AVR Demolition Hammer",
    shortDescription: "Premium breaker reserved for high-load site tasks and service.",
    description: "High-output Hilti breaker maintained on a service cycle for intensive demolition and anchor preparation tasks.",
    brand: "Hilti",
    model: "TE 1000-AVR",
    dailyPrice: 60,
    depositAmount: 320,
    quantityTotal: 3,
    baseQuantityAvailable: 0,
    power: 1.75,
    weight: 12.5,
    status: EquipmentStatus.MAINTENANCE,
    isFeatured: false,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Impact energy", value: "26", unit: "J" },
      { name: "Service status", value: "Maintenance rotation" },
      { name: "Noise level", value: "96", unit: "dB" },
      { name: "Recommended use", value: "Structural demolition" },
    ],
  }),
  equipment({
    categorySlug: "demolition-hammers",
    slug: "milwaukee-kango-950-s",
    name: "Milwaukee Kango 950 S",
    shortDescription: "Robust demolition tool for channels, concrete edges, and openings.",
    description: "Site-ready breaker often used for expansion joints, cable channels, and mechanical room reconstruction.",
    brand: "Milwaukee",
    model: "Kango 950 S",
    dailyPrice: 50,
    depositAmount: 230,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 1.7,
    weight: 11.8,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Blows per minute", value: "1950" },
      { name: "Impact energy", value: "20", unit: "J" },
      { name: "Cord length", value: "6", unit: "m" },
      { name: "Transport case", value: "Yes" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "altrad-belle-minimix-150",
    name: "Altrad Belle Minimix 150",
    shortDescription: "Compact mixer for tile crews, fencing, and small slab repairs.",
    description: "One of the most practical portable mixers for on-site finishing teams and short-cycle repair jobs.",
    brand: "Altrad Belle",
    model: "Minimix 150",
    dailyPrice: 35,
    depositAmount: 180,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 0.55,
    weight: 61,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Drum volume", value: "130", unit: "L" },
      { name: "Mix output", value: "90", unit: "L" },
      { name: "Power supply", value: "220", unit: "V" },
      { name: "Drive type", value: "Electric" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "zitrek-b1510-fk",
    name: "Zitrek B1510 FK Mixer",
    shortDescription: "Field mixer for interior finishing and landscaping crews.",
    description: "A practical electric mixer for site prep, small foundations, and concrete-based finishing work.",
    brand: "Zitrek",
    model: "B1510 FK",
    dailyPrice: 30,
    depositAmount: 150,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 0.7,
    weight: 58,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Drum volume", value: "140", unit: "L" },
      { name: "Frame design", value: "Portable wheel base" },
      { name: "Crown material", value: "Cast iron" },
      { name: "Assembly", value: "Quick release drum" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "sturm-cm20160",
    name: "Sturm CM20160 Concrete Mixer",
    shortDescription: "Mid-size mixer for masonry and outdoor pad pouring.",
    description: "A good fit for builders who need steady batch output for fence posts, paving, and slab extensions.",
    brand: "Sturm",
    model: "CM20160",
    dailyPrice: 32,
    depositAmount: 160,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 0.8,
    weight: 65,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Drum volume", value: "160", unit: "L" },
      { name: "Mix output", value: "110", unit: "L" },
      { name: "Motor protection", value: "Thermal relay" },
      { name: "Tilt control", value: "Hand wheel" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "redverg-rd-cm180",
    name: "RedVerg RD-CM180",
    shortDescription: "Site mixer currently reserved from public rental due to motor diagnostics.",
    description: "High-capacity mixer awaiting diagnostics after a motor overheating alert during a long residential pour.",
    brand: "RedVerg",
    model: "RD-CM180",
    dailyPrice: 34,
    depositAmount: 170,
    quantityTotal: 3,
    baseQuantityAvailable: 0,
    power: 0.9,
    weight: 72,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Drum volume", value: "180", unit: "L" },
      { name: "Availability note", value: "Awaiting diagnostics" },
      { name: "Gear ring", value: "Steel" },
      { name: "Transport wheels", value: "Yes" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "patriot-bm-208c",
    name: "Patriot BM 208C Mixer",
    shortDescription: "Large mixer for driveway pours and low-rise concrete crews.",
    description: "A dependable option when the project needs longer mixing cycles and larger concrete batches per shift.",
    brand: "Patriot",
    model: "BM 208C",
    dailyPrice: 38,
    depositAmount: 190,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 1,
    weight: 79,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Drum volume", value: "200", unit: "L" },
      { name: "Mix output", value: "140", unit: "L" },
      { name: "Batch purpose", value: "Large pours" },
      { name: "Power supply", value: "220", unit: "V" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "wacker-neuson-vp1550aw",
    name: "Wacker Neuson VP1550AW",
    shortDescription: "Professional plate compactor for paving base prep and patch repair.",
    description: "Trusted compactor for sidewalks, trench backfill, and dense granular sub-base on urban job sites.",
    brand: "Wacker Neuson",
    model: "VP1550AW",
    dailyPrice: 55,
    depositAmount: 260,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 3.6,
    weight: 90,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Compaction force", value: "15", unit: "kN" },
      { name: "Plate width", value: "500", unit: "mm" },
      { name: "Travel speed", value: "25", unit: "m/min" },
      { name: "Engine type", value: "Petrol" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "huter-vp-90",
    name: "Huter VP-90 Plate Compactor",
    shortDescription: "General-purpose compactor for paths, curbs, and driveway bedding.",
    description: "Compact unit for crews that need agile movement between landscape and small construction tasks.",
    brand: "Huter",
    model: "VP-90",
    dailyPrice: 44,
    depositAmount: 220,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 4.8,
    weight: 88,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Compaction force", value: "13", unit: "kN" },
      { name: "Base plate", value: "530 x 500", unit: "mm" },
      { name: "Fuel tank", value: "3.6", unit: "L" },
      { name: "Starting system", value: "Manual recoil" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "champion-pc9045fh",
    name: "Champion PC9045FH",
    shortDescription: "Site compactor for paving stone bedding and utility trench refill.",
    description: "A stable compactor with folding transport handle, good for landscape teams and paving contractors.",
    brand: "Champion",
    model: "PC9045FH",
    dailyPrice: 46,
    depositAmount: 215,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 4.1,
    weight: 92,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Compaction depth", value: "300", unit: "mm" },
      { name: "Force", value: "15", unit: "kN" },
      { name: "Water tank", value: "No" },
      { name: "Handle", value: "Foldable" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "masalta-ms60-4",
    name: "Masalta MS60-4 Compactor",
    shortDescription: "Light compactor rotated into workshop inspection after a long asphalt season.",
    description: "Compact plate compactor currently off the shelf for preventive bearing and vibration system inspection.",
    brand: "Masalta",
    model: "MS60-4",
    dailyPrice: 39,
    depositAmount: 180,
    quantityTotal: 2,
    baseQuantityAvailable: 0,
    power: 3.1,
    weight: 63,
    status: EquipmentStatus.MAINTENANCE,
    isFeatured: false,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Compaction force", value: "10.5", unit: "kN" },
      { name: "Maintenance note", value: "Vibration unit inspection" },
      { name: "Transport wheels", value: "Optional" },
      { name: "Engine type", value: "Petrol" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "zitrek-cnp-30-2",
    name: "Zitrek CNP 30-2",
    shortDescription: "Heavy compactor for dense base work around road and yard projects.",
    description: "Durable plate compactor for larger compaction tasks where crews need stronger impact and good transport balance.",
    brand: "Zitrek",
    model: "CNP 30-2",
    dailyPrice: 58,
    depositAmount: 270,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 4.8,
    weight: 125,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Compaction force", value: "25", unit: "kN" },
      { name: "Plate size", value: "630 x 400", unit: "mm" },
      { name: "Travel speed", value: "18", unit: "m/min" },
      { name: "Use case", value: "Road base and yard prep" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "honda-eu30is",
    name: "Honda EU30is Inverter Generator",
    shortDescription: "Quiet inverter generator for site offices and sensitive power tools.",
    description: "Premium low-noise generator for finishing crews, mobile offices, and equipment that needs stable current.",
    brand: "Honda",
    model: "EU30is",
    dailyPrice: 70,
    depositAmount: 360,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 3,
    weight: 59,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Rated power", value: "2.8", unit: "kW" },
      { name: "Fuel type", value: "Petrol" },
      { name: "Noise level", value: "57", unit: "dB" },
      { name: "Run time", value: "7", unit: "h" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "fubag-bs-6600-aes",
    name: "Fubag BS 6600 AES",
    shortDescription: "Portable petrol generator for general construction power backup.",
    description: "A proven site generator for welders, pumps, and shared tool circuits on medium-size construction projects.",
    brand: "Fubag",
    model: "BS 6600 AES",
    dailyPrice: 66,
    depositAmount: 330,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 5.5,
    weight: 84,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Rated power", value: "5.0", unit: "kW" },
      { name: "Sockets", value: "2 x 220V" },
      { name: "Starter", value: "Electric" },
      { name: "Tank volume", value: "25", unit: "L" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "hyundai-hhy-7050fe",
    name: "Hyundai HHY 7050FE",
    shortDescription: "Construction generator for backup circuits, pumps, and batch tools.",
    description: "Reliable portable unit with strong frame design for outdoor storage and demanding contractor schedules.",
    brand: "Hyundai",
    model: "HHY 7050FE",
    dailyPrice: 68,
    depositAmount: 340,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 5.5,
    weight: 81,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Rated power", value: "5.0", unit: "kW" },
      { name: "Fuel tank", value: "25", unit: "L" },
      { name: "Run time", value: "8", unit: "h" },
      { name: "Output phase", value: "Single-phase" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "firman-spg6500e2",
    name: "Firman SPG6500E2",
    shortDescription: "Generator paused for alternator inspection after intermittent voltage spikes.",
    description: "High-output petrol generator currently marked unavailable while the alternator and AVR unit are checked.",
    brand: "Firman",
    model: "SPG6500E2",
    dailyPrice: 64,
    depositAmount: 320,
    quantityTotal: 2,
    baseQuantityAvailable: 0,
    power: 5.2,
    weight: 78,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Inspection reason", value: "AVR and alternator test" },
      { name: "Rated power", value: "5.0", unit: "kW" },
      { name: "Fuel type", value: "Petrol" },
      { name: "Transport kit", value: "Wheel set" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "sdmo-technic-7500te",
    name: "SDMO Technic 7500 TE",
    shortDescription: "Three-phase generator for mixed equipment fleets and temporary facilities.",
    description: "A solid option for sites with lighting towers, pumps, and contractor cabins working from one power source.",
    brand: "SDMO",
    model: "Technic 7500 TE",
    dailyPrice: 82,
    depositAmount: 420,
    quantityTotal: 2,
    baseQuantityAvailable: 2,
    power: 6.6,
    weight: 98,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Rated power", value: "6.0", unit: "kVA" },
      { name: "Phase", value: "Three-phase" },
      { name: "Run time", value: "9", unit: "h" },
      { name: "Starter", value: "Electric" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "abac-montecarlo-l20p",
    name: "ABAC Montecarlo L20P",
    shortDescription: "Compact compressor for finishing, fastening, and blow-out work.",
    description: "A mobile compressor suited to interior contractors, carpenters, and service technicians working indoors.",
    brand: "ABAC",
    model: "Montecarlo L20P",
    dailyPrice: 28,
    depositAmount: 140,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 1.5,
    weight: 32,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Receiver volume", value: "50", unit: "L" },
      { name: "Pressure", value: "10", unit: "bar" },
      { name: "Air flow", value: "220", unit: "L/min" },
      { name: "Portability", value: "Wheel base" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "fubag-vcf-100-cm3",
    name: "Fubag VCF 100 CM3",
    shortDescription: "Belt-drive compressor for pneumatic tools and small paint jobs.",
    description: "Popular compressor for bodywork, workshop support, and framing crews using impact and nail tools.",
    brand: "Fubag",
    model: "VCF 100 CM3",
    dailyPrice: 36,
    depositAmount: 175,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 2.2,
    weight: 64,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Receiver volume", value: "100", unit: "L" },
      { name: "Air flow", value: "440", unit: "L/min" },
      { name: "Drive type", value: "Belt" },
      { name: "Pressure", value: "10", unit: "bar" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "remeza-sb4-c-50-lb30a",
    name: "Remeza SB4/C-50.LB30A",
    shortDescription: "Workshop compressor for pneumatic installation and maintenance teams.",
    description: "A durable Belarus-made compressor that works well for finish carpentry, servicing, and daily tool support.",
    brand: "Remeza",
    model: "SB4/C-50.LB30A",
    dailyPrice: 30,
    depositAmount: 150,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 1.8,
    weight: 39,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Receiver volume", value: "50", unit: "L" },
      { name: "Air flow", value: "420", unit: "L/min" },
      { name: "Pressure switch", value: "Automatic" },
      { name: "Country of assembly", value: "Belarus" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "patriot-euro-50-260k",
    name: "Patriot EURO 50/260K",
    shortDescription: "Compressor not currently available because of valve block replacement.",
    description: "Entry-level air compressor temporarily removed from rental after a planned valve block replacement.",
    brand: "Patriot",
    model: "EURO 50/260K",
    dailyPrice: 24,
    depositAmount: 120,
    quantityTotal: 3,
    baseQuantityAvailable: 0,
    power: 1.8,
    weight: 27,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Receiver volume", value: "50", unit: "L" },
      { name: "Air flow", value: "260", unit: "L/min" },
      { name: "Repair note", value: "Valve block replacement" },
      { name: "Drive type", value: "Direct" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "metabo-basic-250-24w",
    name: "Metabo Basic 250-24 W OF",
    shortDescription: "Oil-free compressor for clean indoor work and finishing teams.",
    description: "Low-maintenance compressor chosen for interiors, service vans, and spaces where clean air matters.",
    brand: "Metabo",
    model: "Basic 250-24 W OF",
    dailyPrice: 26,
    depositAmount: 125,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 1.5,
    weight: 24,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Receiver volume", value: "24", unit: "L" },
      { name: "Oil-free", value: "Yes" },
      { name: "Air flow", value: "200", unit: "L/min" },
      { name: "Noise level", value: "82", unit: "dB" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "krause-protec-xxl-7m",
    name: "Krause Protec XXL 7 m Tower",
    shortDescription: "Mobile tower scaffold for facade touchups and MEP ceiling access.",
    description: "Professional aluminum tower with quick-lock assembly for contractors working on facades and atriums.",
    brand: "Krause",
    model: "Protec XXL 7 m",
    dailyPrice: 95,
    depositAmount: 500,
    quantityTotal: 2,
    baseQuantityAvailable: 2,
    power: null,
    weight: 178,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Working height", value: "7.3", unit: "m" },
      { name: "Platform size", value: "2.0 x 0.6", unit: "m" },
      { name: "Material", value: "Aluminum" },
      { name: "Usage", value: "Indoor and facade work" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "virastar-vs-tower-6m",
    name: "Virastar VS Tower 6 m",
    shortDescription: "Modular tower for installation, painting, and warehouse maintenance.",
    description: "A lightweight aluminum tower that fits indoor service teams and medium-height finishing projects.",
    brand: "Virastar",
    model: "VS Tower 6 m",
    dailyPrice: 82,
    depositAmount: 440,
    quantityTotal: 2,
    baseQuantityAvailable: 2,
    power: null,
    weight: 145,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Working height", value: "6.2", unit: "m" },
      { name: "Platform load", value: "200", unit: "kg" },
      { name: "Assembly time", value: "20", unit: "min" },
      { name: "Transport mode", value: "Compact sections" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "layher-zifa-compact",
    name: "Layher Zifa Compact",
    shortDescription: "Compact stairwell tower for indoor finishing and service access.",
    description: "Specialized compact tower system for narrow spaces, stairwells, and commercial fit-out work.",
    brand: "Layher",
    model: "Zifa Compact",
    dailyPrice: 88,
    depositAmount: 460,
    quantityTotal: 1,
    baseQuantityAvailable: 1,
    power: null,
    weight: 96,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Working height", value: "4.9", unit: "m" },
      { name: "Frame width", value: "0.85", unit: "m" },
      { name: "Application", value: "Stairwells and interiors" },
      { name: "Material", value: "Aluminum" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "euro-scaffold-rolling-75x190",
    name: "Euro Scaffold Rolling Tower 75x190",
    shortDescription: "Tower scaffold set currently held for internal inspection and inventory audit.",
    description: "Rolling scaffold set temporarily paused from rental until a full inventory and locking pin audit is finished.",
    brand: "Euro Scaffold",
    model: "75x190",
    dailyPrice: 76,
    depositAmount: 390,
    quantityTotal: 2,
    baseQuantityAvailable: 0,
    power: null,
    weight: 128,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Inspection note", value: "Inventory and locking pin audit" },
      { name: "Working height", value: "5.4", unit: "m" },
      { name: "Platform width", value: "0.75", unit: "m" },
      { name: "Material", value: "Aluminum" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "steel-frame-facade-kit-12m",
    name: "Steel Frame Facade Kit 12 m",
    shortDescription: "Legacy facade scaffold kit kept in archive for compatibility checks.",
    description: "Archived scaffold set retained only for historical records and dimension matching against old client documentation.",
    brand: "BuildRent Legacy",
    model: "Facade Kit 12 m",
    dailyPrice: 110,
    depositAmount: 600,
    quantityTotal: 1,
    baseQuantityAvailable: 0,
    power: null,
    weight: 420,
    status: EquipmentStatus.ARCHIVED,
    isFeatured: false,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Archive note", value: "Not offered for new rentals" },
      { name: "Working height", value: "12", unit: "m" },
      { name: "Material", value: "Steel" },
      { name: "Sections", value: "Facade frame set" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "esab-rogue-es-200i",
    name: "ESAB Rogue ES 200i",
    shortDescription: "Compact inverter welder for fabrication teams and repair crews.",
    description: "High-efficiency welding inverter for mobile welders handling gates, frames, reinforcement, and repairs.",
    brand: "ESAB",
    model: "Rogue ES 200i",
    dailyPrice: 40,
    depositAmount: 190,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 7.1,
    weight: 8.4,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Welding current", value: "200", unit: "A" },
      { name: "Electrode diameter", value: "4", unit: "mm" },
      { name: "Input voltage", value: "220", unit: "V" },
      { name: "Protection class", value: "IP23S" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "svarog-real-arc-200-black",
    name: "Svarog REAL ARC 200 Black",
    shortDescription: "Field inverter for installers, steel stairs, and support structures.",
    description: "A portable welding machine valued for stable arc performance on repair jobs and custom steel fabrication.",
    brand: "Svarog",
    model: "REAL ARC 200 Black",
    dailyPrice: 34,
    depositAmount: 165,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 6.6,
    weight: 4.7,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Welding current", value: "200", unit: "A" },
      { name: "Duty cycle", value: "60", unit: "%" },
      { name: "Hot start", value: "Yes" },
      { name: "Arc force", value: "Adjustable" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "foxweld-master-202m",
    name: "FoxWeld Master 202M",
    shortDescription: "General-purpose inverter for site fabrication and maintenance.",
    description: "A versatile welding inverter used for canopies, brackets, and quick structural repairs around the site.",
    brand: "FoxWeld",
    model: "Master 202M",
    dailyPrice: 32,
    depositAmount: 150,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 6.3,
    weight: 5.2,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Welding current", value: "200", unit: "A" },
      { name: "Display", value: "Digital" },
      { name: "Electrode diameter", value: "5", unit: "mm" },
      { name: "Cooling", value: "Forced air" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "resanta-sai-220",
    name: "Resanta SAI-220",
    shortDescription: "Inverter under preventive service after fan and cable inspection.",
    description: "Popular welding machine temporarily rotated out while fan bearings and output cables are being checked.",
    brand: "Resanta",
    model: "SAI-220",
    dailyPrice: 29,
    depositAmount: 145,
    quantityTotal: 3,
    baseQuantityAvailable: 0,
    power: 7.2,
    weight: 4.9,
    status: EquipmentStatus.MAINTENANCE,
    isFeatured: false,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Maintenance note", value: "Fan and cable inspection" },
      { name: "Welding current", value: "220", unit: "A" },
      { name: "Voltage range", value: "140-260", unit: "V" },
      { name: "Cooling", value: "Forced" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "aurora-stickmate-250",
    name: "Aurora Stickmate 250",
    shortDescription: "Higher-output inverter for thicker steel and fabrication batches.",
    description: "A dependable welding option for workshops and construction crews working with heavier metal profiles.",
    brand: "Aurora",
    model: "Stickmate 250",
    dailyPrice: 45,
    depositAmount: 205,
    quantityTotal: 2,
    baseQuantityAvailable: 2,
    power: 8.5,
    weight: 7.8,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Welding current", value: "250", unit: "A" },
      { name: "Duty cycle", value: "60", unit: "%" },
      { name: "Electrode diameter", value: "6", unit: "mm" },
      { name: "Application", value: "Heavy steel profiles" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "stihl-ts-420",
    name: "Stihl TS 420 Cut-Off Saw",
    shortDescription: "Handheld concrete and metal cutter for openings, curbs, and pipes.",
    description: "Highly mobile cut-off saw for rescue openings, paving adjustments, steel sections, and utility work.",
    brand: "Stihl",
    model: "TS 420",
    dailyPrice: 58,
    depositAmount: 280,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 3.2,
    weight: 9.6,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Disc diameter", value: "350", unit: "mm" },
      { name: "Cutting depth", value: "125", unit: "mm" },
      { name: "Engine type", value: "Petrol" },
      { name: "Water connection", value: "Yes" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "husqvarna-k770",
    name: "Husqvarna K 770 Cutter",
    shortDescription: "Universal disc cutter for asphalt, curb stone, and reinforcement work.",
    description: "Reliable high-output saw used by utility crews, paving teams, and general contractors on dense materials.",
    brand: "Husqvarna",
    model: "K 770",
    dailyPrice: 62,
    depositAmount: 300,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 3.7,
    weight: 10.1,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Disc diameter", value: "350", unit: "mm" },
      { name: "Cutting depth", value: "125", unit: "mm" },
      { name: "Power source", value: "Petrol" },
      { name: "Use case", value: "Concrete and steel" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "makita-lc1230",
    name: "Makita LC1230 Metal Saw",
    shortDescription: "Cold-cut metal saw for profiles, channels, and site fabrication.",
    description: "Accurate metal cutting saw for workshop corners and mobile fabrication tasks where clean edges matter.",
    brand: "Makita",
    model: "LC1230",
    dailyPrice: 37,
    depositAmount: 170,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 1.75,
    weight: 19.3,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Blade diameter", value: "305", unit: "mm" },
      { name: "Cut type", value: "Cold cut" },
      { name: "Material", value: "Metal profiles" },
      { name: "Power supply", value: "220", unit: "V" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "eibenstock-ees-1400-3",
    name: "Eibenstock EES 1400-3 Wall Chaser",
    shortDescription: "Wall chaser unavailable while blade guards are being replaced.",
    description: "Specialized chasing tool currently not rentable until guard hardware and dust seals are replaced.",
    brand: "Eibenstock",
    model: "EES 1400-3",
    dailyPrice: 41,
    depositAmount: 190,
    quantityTotal: 2,
    baseQuantityAvailable: 0,
    power: 1.4,
    weight: 4.7,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Blade set", value: "Twin disc" },
      { name: "Cut width", value: "10-40", unit: "mm" },
      { name: "Repair note", value: "Blade guard replacement" },
      { name: "Dust extraction", value: "Supported" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "legacy-asphalt-saw-500",
    name: "Legacy Asphalt Saw 500",
    shortDescription: "Archived road saw retained only for old contract reference.",
    description: "Historical equipment record preserved for reporting and documentation of earlier municipal projects.",
    brand: "BuildRent Legacy",
    model: "Asphalt Saw 500",
    dailyPrice: 85,
    depositAmount: 430,
    quantityTotal: 1,
    baseQuantityAvailable: 0,
    power: 9,
    weight: 115,
    status: EquipmentStatus.ARCHIVED,
    isFeatured: false,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Archive note", value: "Historical record only" },
      { name: "Disc diameter", value: "500", unit: "mm" },
      { name: "Engine type", value: "Petrol" },
      { name: "Use case", value: "Road repairs" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "bosch-gll-3-80-cg",
    name: "Bosch GLL 3-80 CG Laser Level",
    shortDescription: "Green-beam laser for interior layout and suspended ceiling work.",
    description: "Highly visible laser level for partition framing, suspended ceilings, tiling, and cabinet alignment.",
    brand: "Bosch",
    model: "GLL 3-80 CG",
    dailyPrice: 24,
    depositAmount: 120,
    quantityTotal: 6,
    baseQuantityAvailable: 6,
    power: null,
    weight: 0.9,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Range", value: "30", unit: "m" },
      { name: "Beam color", value: "Green" },
      { name: "Accuracy", value: "+/- 0.2", unit: "mm/m" },
      { name: "Bluetooth", value: "Yes" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "leica-rugby-620",
    name: "Leica Rugby 620 Rotary Laser",
    shortDescription: "Outdoor rotary laser for grading, utilities, and site leveling.",
    description: "A professional-grade rotary laser used on larger plots, foundations, and exterior utility alignment.",
    brand: "Leica",
    model: "Rugby 620",
    dailyPrice: 48,
    depositAmount: 260,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: null,
    weight: 2.4,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Range", value: "800", unit: "m" },
      { name: "Protection", value: "IP67" },
      { name: "Accuracy", value: "+/- 1.5", unit: "mm at 30 m" },
      { name: "Application", value: "Outdoor grading" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "stanley-tlm330",
    name: "Stanley TLM330 Distance Meter",
    shortDescription: "Compact laser meter for quick room, facade, and opening measurements.",
    description: "Convenient handheld range finder for finish estimators, survey support, and installation planning.",
    brand: "Stanley",
    model: "TLM330",
    dailyPrice: 12,
    depositAmount: 60,
    quantityTotal: 8,
    baseQuantityAvailable: 8,
    power: null,
    weight: 0.18,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Range", value: "100", unit: "m" },
      { name: "Accuracy", value: "+/- 1.5", unit: "mm" },
      { name: "Display", value: "Backlit" },
      { name: "Functions", value: "Area and volume" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "ada-cube-360-home",
    name: "ADA Cube 360 Home Edition",
    shortDescription: "Laser level paused from rental because of calibration drift.",
    description: "Compact laser level currently awaiting calibration after drift was detected during a quality check.",
    brand: "ADA",
    model: "Cube 360 Home Edition",
    dailyPrice: 10,
    depositAmount: 45,
    quantityTotal: 5,
    baseQuantityAvailable: 0,
    power: null,
    weight: 0.35,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Calibration note", value: "Pending calibration" },
      { name: "Range", value: "20", unit: "m" },
      { name: "Beam planes", value: "1 x 360 deg" },
      { name: "Tripod thread", value: "1/4" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "trimble-m3-total-station",
    name: "Trimble M3 Total Station",
    shortDescription: "Survey-grade station for site layout, axes transfer, and geodesy support.",
    description: "A precision instrument for contractors that need complex geometry transfer and accurate site control.",
    brand: "Trimble",
    model: "M3",
    dailyPrice: 120,
    depositAmount: 700,
    quantityTotal: 1,
    baseQuantityAvailable: 1,
    power: null,
    weight: 4.5,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Angular accuracy", value: "5", unit: "sec" },
      { name: "Range with prism", value: "3000", unit: "m" },
      { name: "Storage", value: "Internal memory" },
      { name: "Use case", value: "Construction layout" },
    ],
  }),
];
