import { EquipmentStatus } from "@prisma/client";

export type SeedEquipmentImage = {
  url: string;
  alt: string;
  sortOrder: number;
};

export type SeedEquipmentSpec = {
  name: string;
  value: string;
  unit?: string | null;
};

export type SeedEquipment = {
  categorySlug: string;
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  brand: string;
  model: string;
  dailyPrice: number;
  depositAmount: number;
  quantityTotal: number;
  baseQuantityAvailable: number;
  power: number | null;
  weight: number | null;
  status: EquipmentStatus;
  isFeatured: boolean;
  images: SeedEquipmentImage[];
  specs: SeedEquipmentSpec[];
};

type EquipmentFactoryInput = Omit<SeedEquipment, "images" | "specs"> & {
  imageUrls: string[];
  specs: SeedEquipmentSpec[];
};

function buildImages(name: string, imageUrls: string[]): SeedEquipmentImage[] {
  return imageUrls.map((url, index) => ({
    url,
    alt: `Фото оборудования ${name} (${index + 1})`,
    sortOrder: index,
  }));
}

function equipment(input: EquipmentFactoryInput): SeedEquipment {
  return {
    ...input,
    images: buildImages(input.name, input.imageUrls),
  };
}

const imageLibrary = {
  demolition: [
    "https://images.unsplash.com/photo-1755168648692-ef8937b7e63e?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1679797870465-b4eda40ead96?auto=format&fit=crop&w=1200&q=80",
  ],
  mixer: [
    "https://images.unsplash.com/photo-1751221701301-b02ca1b4b49e?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1770822662967-7f66605f9103?auto=format&fit=crop&w=1200&q=80",
  ],
  compactor: [
    "https://images.unsplash.com/photo-1776381733574-372689e246b4?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1760708626681-59a5373819a6?auto=format&fit=crop&w=1200&q=80",
  ],
  generator: [
    "https://images.unsplash.com/photo-1759692071712-adc78a8516c8?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1653878729171-efea1af9e7a8?auto=format&fit=crop&w=1200&q=80",
  ],
  compressor: [
    "https://images.unsplash.com/photo-1542486500-db3f713278bc?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1655165312002-9d781ad4046e?auto=format&fit=crop&w=1200&q=80",
  ],
  scaffolding: [
    "https://images.unsplash.com/photo-1760597307051-67946f9cf865?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1741916541913-7203d2be5e6e?auto=format&fit=crop&w=1200&q=80",
  ],
  welding: [
    "https://images.unsplash.com/photo-1473090928358-00fcead4f08c?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1726421690313-2e0519335b82?auto=format&fit=crop&w=1200&q=80",
  ],
  saws: [
    "https://images.unsplash.com/photo-1723117799189-ab87698c8938?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1505855796860-aa05646cbf1f?auto=format&fit=crop&w=1200&q=80",
  ],
  measuring: [
    "https://images.unsplash.com/photo-1771068807150-2cab0734d25b?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1770822662903-aa69f6aa9b03?auto=format&fit=crop&w=1200&q=80",
  ],
} satisfies Record<string, string[]>;

export const EQUIPMENT_SEEDS: SeedEquipment[] = [
  equipment({
    categorySlug: "demolition-hammers",
    slug: "bosch-gbh-8-45dv",
    name: "Bosch GBH 8-45 DV Rotary Hammer",
    shortDescription: "Профессиональный молоток SDS-max для сверления анкеров и тяжелого долбления.",
    description: "Надежный перфоратор для фасадных работ, проемов и сверления железобетона на активных строительных площадках.",
    brand: "Bosch",
    model: "GBH 8-45 DV",
    dailyPrice: 45,
    depositAmount: 220,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 1.5,
    weight: 8.9,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Энергия удара", value: "12.5", unit: "J" },
      { name: "Тип патрона", value: "SDS-max" },
      { name: "Диаметр сверления", value: "45", unit: "mm" },
      { name: "Режим работы", value: "Сверление и долбление" },
    ],
  }),
  equipment({
    categorySlug: "demolition-hammers",
    slug: "makita-hm1214c",
    name: "Makita HM1214C Demolition Hammer",
    shortDescription: "Компактный демонтажный молоток для штробления стен и снятия плитки.",
    description: "Сбалансированный молоток для ежедневных отделочных бригад, которым необходима надежная сила удара без необходимости транспортировки больших размеров.",
    brand: "Makita",
    model: "HM1214C",
    dailyPrice: 42,
    depositAmount: 210,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 1.5,
    weight: 12.3,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Энергия удара", value: "19.9", unit: "J" },
      { name: "Контроль вибрации", value: "AVT" },
      { name: "Напряжение", value: "220", unit: "V" },
      { name: "Чехол в комплекте", value: "Да" },
    ],
  }),
  equipment({
    categorySlug: "demolition-hammers",
    slug: "dewalt-d25902k",
    name: "DeWalt D25902K Breaker",
    shortDescription: "Тяжелый отбойный молоток для снятия плит и разборки кирпича.",
    description: "Мощный отбойный молоток для бригад по сносу, работающих на армированных плитах, каналах и стенах из плотной кладки.",
    brand: "DeWalt",
    model: "D25902K",
    dailyPrice: 48,
    depositAmount: 240,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 1.55,
    weight: 10.5,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Энергия удара", value: "19", unit: "J" },
      { name: "Держатель инструмента", value: "SDS-max" },
      { name: "Ударов в минуту", value: "2100" },
      { name: "Вариант использования", value: "Снос перекрытий и стен" },
    ],
  }),
  equipment({
    categorySlug: "demolition-hammers",
    slug: "hilti-te-1000-avr",
    name: "Hilti TE 1000-AVR Demolition Hammer",
    shortDescription: "Премиум-прерыватель, зарезервированный для задач и обслуживания сайта с высокой нагрузкой.",
    description: "Высокопроизводительный гидромолот Hilti, поддерживающий цикл обслуживания для выполнения интенсивных задач по сносу и подготовке анкеров.",
    brand: "Hilti",
    model: "TE 1000-AVR",
    dailyPrice: 60,
    depositAmount: 320,
    quantityTotal: 3,
    baseQuantityAvailable: 0,
    power: 1.75,
    weight: 12.5,
    status: EquipmentStatus.MAINTENANCE,
    isFeatured: false,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Энергия удара", value: "26", unit: "J" },
      { name: "Статус услуги", value: "Ротация технического обслуживания" },
      { name: "Уровень шума", value: "96", unit: "dB" },
      { name: "Рекомендуемое использование", value: "Структурный снос" },
    ],
  }),
  equipment({
    categorySlug: "demolition-hammers",
    slug: "milwaukee-kango-950-s",
    name: "Milwaukee Kango 950 S",
    shortDescription: "Прочный инструмент для разрушения каналов, бетонных кромок и проемов.",
    description: "Готовый к эксплуатации выключатель часто используется для компенсаторов, кабельных каналов и реконструкции технических помещений.",
    brand: "Milwaukee",
    model: "Kango 950 S",
    dailyPrice: 50,
    depositAmount: 230,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 1.7,
    weight: 11.8,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.demolition,
    specs: [
      { name: "Ударов в минуту", value: "1950" },
      { name: "Энергия удара", value: "20", unit: "J" },
      { name: "Длина шнура", value: "6", unit: "m" },
      { name: "Транспортировочный кейс", value: "Да" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "altrad-belle-minimix-150",
    name: "Altrad Belle Minimix 150",
    shortDescription: "Компактный миксер для работ по укладке плитки, ограждений и мелкого ремонта плит.",
    description: "Один из самых практичных портативных миксеров для выездных отделочных бригад и ремонтных работ с коротким циклом.",
    brand: "Altrad Belle",
    model: "Minimix 150",
    dailyPrice: 35,
    depositAmount: 180,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 0.55,
    weight: 61,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Громкость барабана", value: "130", unit: "L" },
      { name: "Смешать выход", value: "90", unit: "L" },
      { name: "Источник питания", value: "220", unit: "V" },
      { name: "Тип привода", value: "Электрический" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "zitrek-b1510-fk",
    name: "Zitrek B1510 FK Mixer",
    shortDescription: "Полевой миксер для бригад по внутренней отделке и ландшафтному дизайну.",
    description: "Практичный электрический миксер для подготовки площадки, закладки небольшого фундамента и отделочных работ по бетону.",
    brand: "Zitrek",
    model: "B1510 FK",
    dailyPrice: 30,
    depositAmount: 150,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 0.7,
    weight: 58,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Громкость барабана", value: "140", unit: "L" },
      { name: "Конструкция рамы", value: "Переносная колесная база" },
      { name: "Материал коронки", value: "Чугун" },
      { name: "Сборка", value: "Быстросъемный барабан" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "sturm-cm20160",
    name: "Sturm CM20160 Concrete Mixer",
    shortDescription: "Смеситель среднего размера для заливки кладки и наружных работ.",
    description: "Идеально подходит для строителей, которым необходима стабильная производительность при изготовлении столбов забора, тротуарной плитки и расширений плит.",
    brand: "Sturm",
    model: "CM20160",
    dailyPrice: 32,
    depositAmount: 160,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 0.8,
    weight: 65,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Громкость барабана", value: "160", unit: "L" },
      { name: "Смешать выход", value: "110", unit: "L" },
      { name: "Защита двигателя", value: "Тепловое реле" },
      { name: "Контроль наклона", value: "Маховик" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "redverg-rd-cm180",
    name: "RedVerg RD-CM180",
    shortDescription: "Миксер на данный момент зарезервирован из публичной аренды в связи с диагностикой двигателя.",
    description: "Высокопроизводительный миксер ожидает диагностики после предупреждения о перегреве двигателя во время длительной заливки в жилом помещении.",
    brand: "RedVerg",
    model: "RD-CM180",
    dailyPrice: 34,
    depositAmount: 170,
    quantityTotal: 3,
    baseQuantityAvailable: 0,
    power: 0.9,
    weight: 72,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Громкость барабана", value: "180", unit: "L" },
      { name: "Примечание о наличии", value: "Ожидание диагностики" },
      { name: "Зубчатое кольцо", value: "Сталь" },
      { name: "Транспортные колеса", value: "Да" },
    ],
  }),
  equipment({
    categorySlug: "concrete-mixers",
    slug: "patriot-bm-208c",
    name: "Patriot BM 208C Mixer",
    shortDescription: "Большой миксер для заливки подъездных дорог и малоэтажных бетонных бригад.",
    description: "Надежный вариант, когда проект требует более длительных циклов смешивания и больших порций бетона за смену.",
    brand: "Patriot",
    model: "BM 208C",
    dailyPrice: 38,
    depositAmount: 190,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 1,
    weight: 79,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.mixer,
    specs: [
      { name: "Громкость барабана", value: "200", unit: "L" },
      { name: "Смешать выход", value: "140", unit: "L" },
      { name: "Назначение пакета", value: "Большие заливки" },
      { name: "Источник питания", value: "220", unit: "V" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "wacker-neuson-vp1550aw",
    name: "Wacker Neuson VP1550AW",
    shortDescription: "Профессиональный виброплита для подготовки основания тротуарной плитки и ремонта ямочного покрытия.",
    description: "Надежный уплотнитель для тротуаров, засыпки траншей и плотного гранулированного основания на городских строительных площадках.",
    brand: "Wacker Neuson",
    model: "VP1550AW",
    dailyPrice: 55,
    depositAmount: 260,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 3.6,
    weight: 90,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Сила уплотнения", value: "15", unit: "kN" },
      { name: "Ширина пластины", value: "500", unit: "mm" },
      { name: "Скорость движения", value: "25", unit: "m/min" },
      { name: "Тип двигателя", value: "Бензин" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "huter-vp-90",
    name: "Huter VP-90 Plate Compactor",
    shortDescription: "Универсальный уплотнитель для дорожек, бордюров и подъездных дорожек.",
    description: "Компактное устройство для бригад, которым необходимо быстрое перемещение между ландшафтными работами и небольшими строительными задачами.",
    brand: "Huter",
    model: "VP-90",
    dailyPrice: 44,
    depositAmount: 220,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 4.8,
    weight: 88,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Сила уплотнения", value: "13", unit: "kN" },
      { name: "Опорная пластина", value: "530 x 500", unit: "mm" },
      { name: "Топливный бак", value: "3.6", unit: "L" },
      { name: "Стартовая система", value: "Ручная отдача" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "champion-pc9045fh",
    name: "Champion PC9045FH",
    shortDescription: "Уплотнитель площадки для укладки брусчатки и засыпки траншей.",
    description: "Стабильный уплотнитель со складной ручкой для транспортировки, подходящий для ландшафтных бригад и подрядчиков по укладке дорожного покрытия.",
    brand: "Champion",
    model: "PC9045FH",
    dailyPrice: 46,
    depositAmount: 215,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 4.1,
    weight: 92,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Глубина уплотнения", value: "300", unit: "mm" },
      { name: "Сила", value: "15", unit: "kN" },
      { name: "Резервуар для воды", value: "Нет" },
      { name: "Ручка", value: "Складной" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "masalta-ms60-4",
    name: "Masalta MS60-4 Compactor",
    shortDescription: "Легкий каток был отправлен на техосмотр в мастерскую после долгого асфальтового сезона.",
    description: "В настоящее время в продаже имеется компактный виброплита для профилактического осмотра подшипников и систем вибрации.",
    brand: "Masalta",
    model: "MS60-4",
    dailyPrice: 39,
    depositAmount: 180,
    quantityTotal: 2,
    baseQuantityAvailable: 0,
    power: 3.1,
    weight: 63,
    status: EquipmentStatus.MAINTENANCE,
    isFeatured: false,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Сила уплотнения", value: "10.5", unit: "kN" },
      { name: "Примечание по обслуживанию", value: "Проверка виброблока" },
      { name: "Транспортные колеса", value: "Необязательный" },
      { name: "Тип двигателя", value: "Бензин" },
    ],
  }),
  equipment({
    categorySlug: "plate-compactors",
    slug: "zitrek-cnp-30-2",
    name: "Zitrek CNP 30-2",
    shortDescription: "Тяжелый каток для работы на плотных основаниях на дорогах и дворах.",
    description: "Прочный виброплита для более масштабных задач по уплотнению, когда бригадам требуется более сильный удар и хороший транспортный баланс.",
    brand: "Zitrek",
    model: "CNP 30-2",
    dailyPrice: 58,
    depositAmount: 270,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 4.8,
    weight: 125,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compactor,
    specs: [
      { name: "Сила уплотнения", value: "25", unit: "kN" },
      { name: "Размер пластины", value: "630 x 400", unit: "mm" },
      { name: "Скорость движения", value: "18", unit: "m/min" },
      { name: "Вариант использования", value: "Подготовка дорожного основания и двора" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "honda-eu30is",
    name: "Honda EU30is Inverter Generator",
    shortDescription: "Тихий инверторный генератор для офисов и чувствительных электроинструментов.",
    description: "Малошумящий генератор премиум-класса для отделочных бригад, мобильных офисов и оборудования, требующего стабильного тока.",
    brand: "Honda",
    model: "EU30is",
    dailyPrice: 70,
    depositAmount: 360,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 3,
    weight: 59,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Номинальная мощность", value: "2.8", unit: "kW" },
      { name: "Тип топлива", value: "Бензин" },
      { name: "Уровень шума", value: "57", unit: "dB" },
      { name: "Время выполнения", value: "7", unit: "ч" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "fubag-bs-6600-aes",
    name: "Fubag BS 6600 AES",
    shortDescription: "Переносной бензиновый генератор для резервного электроснабжения общестроительных работ.",
    description: "Проверенный генератор для сварщиков, насосов и общих цепей инструментов на строительных проектах среднего размера.",
    brand: "Fubag",
    model: "BS 6600 AES",
    dailyPrice: 66,
    depositAmount: 330,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 5.5,
    weight: 84,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Номинальная мощность", value: "5.0", unit: "kW" },
      { name: "Розетки", value: "2 x 220V" },
      { name: "Стартер", value: "Электрический" },
      { name: "Объем бака", value: "25", unit: "L" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "hyundai-hhy-7050fe",
    name: "Hyundai HHY 7050FE",
    shortDescription: "Строительный генератор для резервных цепей, насосов и дозировочного оборудования.",
    description: "Надежное портативное устройство с прочной рамой для хранения на открытом воздухе и жестких графиков работы подрядчиков.",
    brand: "Hyundai",
    model: "HHY 7050FE",
    dailyPrice: 68,
    depositAmount: 340,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 5.5,
    weight: 81,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Номинальная мощность", value: "5.0", unit: "kW" },
      { name: "Топливный бак", value: "25", unit: "L" },
      { name: "Время выполнения", value: "8", unit: "ч" },
      { name: "Выходная фаза", value: "Однофазный" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "firman-spg6500e2",
    name: "Firman SPG6500E2",
    shortDescription: "Генератор был остановлен для проверки генератора переменного тока после периодических скачков напряжения.",
    description: "Бензиновый генератор высокой мощности в настоящее время помечен как недоступный, пока проверяются генератор и блок AVR.",
    brand: "Firman",
    model: "SPG6500E2",
    dailyPrice: 64,
    depositAmount: 320,
    quantityTotal: 2,
    baseQuantityAvailable: 0,
    power: 5.2,
    weight: 78,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Причина проверки", value: "Проверка AVR и альтернатора" },
      { name: "Номинальная мощность", value: "5.0", unit: "kW" },
      { name: "Тип топлива", value: "Бензин" },
      { name: "Транспортный комплект", value: "Комплект колес" },
    ],
  }),
  equipment({
    categorySlug: "generators",
    slug: "sdmo-technic-7500te",
    name: "SDMO Technic 7500 TE",
    shortDescription: "Трехфазный генератор для смешанного парка оборудования и временных объектов.",
    description: "Надежный вариант для объектов с осветительными башнями, насосами и домиками подрядчиков, работающими от одного источника питания.",
    brand: "SDMO",
    model: "Technic 7500 TE",
    dailyPrice: 82,
    depositAmount: 420,
    quantityTotal: 2,
    baseQuantityAvailable: 2,
    power: 6.6,
    weight: 98,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.generator,
    specs: [
      { name: "Номинальная мощность", value: "6.0", unit: "kVA" },
      { name: "Фаза", value: "Трехфазный" },
      { name: "Время выполнения", value: "9", unit: "ч" },
      { name: "Стартер", value: "Электрический" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "abac-montecarlo-l20p",
    name: "ABAC Montecarlo L20P",
    shortDescription: "Компактный компрессор для отделочных, крепежных и продувочных работ.",
    description: "Мобильный компрессор, подходящий для подрядчиков по внутренней отделке, плотников и специалистов по техническому обслуживанию, работающих внутри помещений.",
    brand: "ABAC",
    model: "Montecarlo L20P",
    dailyPrice: 28,
    depositAmount: 140,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 1.5,
    weight: 32,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Объем ресивера", value: "50", unit: "L" },
      { name: "Давление", value: "10", unit: "бар" },
      { name: "Расход воздуха", value: "220", unit: "L/min" },
      { name: "Портативность", value: "Колесная база" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "fubag-vcf-100-cm3",
    name: "Fubag VCF 100 CM3",
    shortDescription: "Компрессор с ременным приводом для пневматических инструментов и небольших покрасочных работ.",
    description: "Популярный компрессор для кузовных работ, поддержки мастерских и бригад, использующих ударные инструменты и гвозди.",
    brand: "Fubag",
    model: "VCF 100 CM3",
    dailyPrice: 36,
    depositAmount: 175,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 2.2,
    weight: 64,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Объем ресивера", value: "100", unit: "L" },
      { name: "Расход воздуха", value: "440", unit: "L/min" },
      { name: "Тип привода", value: "Пояс" },
      { name: "Давление", value: "10", unit: "бар" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "remeza-sb4-c-50-lb30a",
    name: "Remeza SB4/C-50.LB30A",
    shortDescription: "Компрессор для цеха для бригад пневматического монтажа и обслуживания.",
    description: "Надежный компрессор белорусского производства, который хорошо подходит для отделочных столярных работ, обслуживания и ежедневного обслуживания инструментов.",
    brand: "Remeza",
    model: "SB4/C-50.LB30A",
    dailyPrice: 30,
    depositAmount: 150,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 1.8,
    weight: 39,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Объем ресивера", value: "50", unit: "L" },
      { name: "Расход воздуха", value: "420", unit: "L/min" },
      { name: "Реле давления", value: "Автоматический" },
      { name: "Страна сборки", value: "Беларусь" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "patriot-euro-50-260k",
    name: "Patriot EURO 50/260K",
    shortDescription: "Компрессор в настоящее время недоступен из-за замены блока клапанов.",
    description: "Воздушный компрессор начального уровня временно снят с проката после плановой замены блока клапанов.",
    brand: "Patriot",
    model: "EURO 50/260K",
    dailyPrice: 24,
    depositAmount: 120,
    quantityTotal: 3,
    baseQuantityAvailable: 0,
    power: 1.8,
    weight: 27,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Объем ресивера", value: "50", unit: "L" },
      { name: "Расход воздуха", value: "260", unit: "L/min" },
      { name: "Примечание по ремонту", value: "Замена блока клапанов" },
      { name: "Тип привода", value: "Прямой" },
    ],
  }),
  equipment({
    categorySlug: "compressors",
    slug: "metabo-basic-250-24w",
    name: "Metabo Basic 250-24 W OF",
    shortDescription: "Безмасляный компрессор для чистоты рабочих помещений и отделочных бригад.",
    description: "Компрессор, не требующий особого обслуживания, выбран для внутренних помещений, сервисных фургонов и помещений, где важен чистый воздух.",
    brand: "Metabo",
    model: "Basic 250-24 W OF",
    dailyPrice: 26,
    depositAmount: 125,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 1.5,
    weight: 24,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.compressor,
    specs: [
      { name: "Объем ресивера", value: "24", unit: "L" },
      { name: "Без масла", value: "Да" },
      { name: "Расход воздуха", value: "200", unit: "L/min" },
      { name: "Уровень шума", value: "82", unit: "dB" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "krause-protec-xxl-7m",
    name: "Krause Protec XXL 7 m Tower",
    shortDescription: "Передвижные вышки для ремонта фасада и доступа к инженерным системам под потолком.",
    description: "Профессиональная алюминиевая вышка с быстроразъемным монтажом для подрядчиков, работающих на фасадах и атриумах.",
    brand: "Krause",
    model: "Protec XXL 7 m",
    dailyPrice: 95,
    depositAmount: 500,
    quantityTotal: 2,
    baseQuantityAvailable: 2,
    power: null,
    weight: 178,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Рабочая высота", value: "7.3", unit: "m" },
      { name: "Размер платформы", value: "2.0 x 0.6", unit: "m" },
      { name: "Материал", value: "Алюминий" },
      { name: "Использование", value: "Внутренние и фасадные работы" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "virastar-vs-tower-6m",
    name: "Virastar VS Tower 6 m",
    shortDescription: "Модульная вышка для монтажа, покраски и складского обслуживания.",
    description: "Легкая алюминиевая башня, подходящая для обслуживающего персонала и отделочных работ средней высоты.",
    brand: "Virastar",
    model: "VS Tower 6 m",
    dailyPrice: 82,
    depositAmount: 440,
    quantityTotal: 2,
    baseQuantityAvailable: 2,
    power: null,
    weight: 145,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Рабочая высота", value: "6.2", unit: "m" },
      { name: "Нагрузка на платформу", value: "200", unit: "kg" },
      { name: "Время сборки", value: "20", unit: "мин" },
      { name: "Вид транспорта", value: "Компактные секции" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "layher-zifa-compact",
    name: "Layher Zifa Compact",
    shortDescription: "Компактная лестничная башня для внутренней отделки и доступа для обслуживания.",
    description: "Специализированная компактная башенная система для узких помещений, лестничных клеток и коммерческих отделочных работ.",
    brand: "Layher",
    model: "Zifa Compact",
    dailyPrice: 88,
    depositAmount: 460,
    quantityTotal: 1,
    baseQuantityAvailable: 1,
    power: null,
    weight: 96,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Рабочая высота", value: "4.9", unit: "m" },
      { name: "Ширина рамы", value: "0.85", unit: "m" },
      { name: "Область применения", value: "Лестничные клетки и интерьеры" },
      { name: "Материал", value: "Алюминий" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "euro-scaffold-rolling-75x190",
    name: "Euro Scaffold Rolling Tower 75x190",
    shortDescription: "Комплект строительных лесов башни в настоящее время хранится для внутренней проверки и инвентаризации.",
    description: "Сдача в аренду комплекта подвижных лесов временно приостановлена ​​до завершения полной инвентаризации и проверки стопорных штифтов.",
    brand: "Euro Scaffold",
    model: "75x190",
    dailyPrice: 76,
    depositAmount: 390,
    quantityTotal: 2,
    baseQuantityAvailable: 0,
    power: null,
    weight: 128,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Примечание по осмотру", value: "Инвентаризация и аудит стопорных штифтов" },
      { name: "Рабочая высота", value: "5.4", unit: "m" },
      { name: "Ширина платформы", value: "0.75", unit: "m" },
      { name: "Материал", value: "Алюминий" },
    ],
  }),
  equipment({
    categorySlug: "scaffolding-towers",
    slug: "steel-frame-facade-kit-12m",
    name: "Steel Frame Facade Kit 12 m",
    shortDescription: "Устаревший комплект фасадных лесов хранится в архиве для проверки совместимости.",
    description: "Архивированный набор шаблонов сохраняется только для исторических записей и сопоставления измерений со старой клиентской документацией.",
    brand: "BuildRent Legacy",
    model: "Facade Kit 12 m",
    dailyPrice: 110,
    depositAmount: 600,
    quantityTotal: 1,
    baseQuantityAvailable: 0,
    power: null,
    weight: 420,
    status: EquipmentStatus.ARCHIVED,
    isFeatured: false,
    imageUrls: imageLibrary.scaffolding,
    specs: [
      { name: "Архивная заметка", value: "Не предлагается для новых аренд" },
      { name: "Рабочая высота", value: "12", unit: "m" },
      { name: "Материал", value: "Сталь" },
      { name: "Разделы", value: "Комплект фасадного каркаса" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "esab-rogue-es-200i",
    name: "ESAB Rogue ES 200i",
    shortDescription: "Компактный инверторный сварочный аппарат для производственных бригад и ремонтных бригад.",
    description: "Высокопроизводительный сварочный инвертор для мобильных сварщиков, занимающихся работой с воротами, рамами, арматурой и ремонтом.",
    brand: "ESAB",
    model: "Rogue ES 200i",
    dailyPrice: 40,
    depositAmount: 190,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 7.1,
    weight: 8.4,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Сварочный ток", value: "200", unit: "A" },
      { name: "Диаметр электрода", value: "4", unit: "mm" },
      { name: "Входное напряжение", value: "220", unit: "V" },
      { name: "Класс защиты", value: "IP23S" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "svarog-real-arc-200-black",
    name: "Svarog REAL ARC 200 Black",
    shortDescription: "Полевой инвертор для монтажников, стальных лестниц и опорных конструкций.",
    description: "Портативный сварочный аппарат, ценимый за стабильную работу дуги при ремонтных работах и ​​изготовлении стали по индивидуальному заказу.",
    brand: "Svarog",
    model: "REAL ARC 200 Black",
    dailyPrice: 34,
    depositAmount: 165,
    quantityTotal: 5,
    baseQuantityAvailable: 5,
    power: 6.6,
    weight: 4.7,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Сварочный ток", value: "200", unit: "A" },
      { name: "Продолжительность включения", value: "60", unit: "%" },
      { name: "Горячий старт", value: "Да" },
      { name: "Сила дуги", value: "Регулируемый" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "foxweld-master-202m",
    name: "FoxWeld Master 202M",
    shortDescription: "Инвертор общего назначения для изготовления и обслуживания на объекте.",
    description: "Универсальный сварочный инвертор, используемый для навесов, кронштейнов и быстрого ремонта конструкций на объекте.",
    brand: "FoxWeld",
    model: "Master 202M",
    dailyPrice: 32,
    depositAmount: 150,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 6.3,
    weight: 5.2,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Сварочный ток", value: "200", unit: "A" },
      { name: "Отображать", value: "Цифровой" },
      { name: "Диаметр электрода", value: "5", unit: "mm" },
      { name: "Охлаждение", value: "Принудительная вентиляция" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "resanta-sai-220",
    name: "Resanta SAI-220",
    shortDescription: "Инвертор находится на профилактическом обслуживании после проверки вентилятора и кабеля.",
    description: "Популярный сварочный аппарат временно выведен из эксплуатации, пока проверяются подшипники вентилятора и выходные кабели.",
    brand: "Resanta",
    model: "SAI-220",
    dailyPrice: 29,
    depositAmount: 145,
    quantityTotal: 3,
    baseQuantityAvailable: 0,
    power: 7.2,
    weight: 4.9,
    status: EquipmentStatus.MAINTENANCE,
    isFeatured: false,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Примечание по обслуживанию", value: "Проверка вентилятора и кабеля" },
      { name: "Сварочный ток", value: "220", unit: "A" },
      { name: "Диапазон напряжения", value: "140-260", unit: "V" },
      { name: "Охлаждение", value: "Принужденный" },
    ],
  }),
  equipment({
    categorySlug: "welding-equipment",
    slug: "aurora-stickmate-250",
    name: "Aurora Stickmate 250",
    shortDescription: "Инвертор повышенной мощности для работы с толстым металлом и производственных задач.",
    description: "Надёжный сварочный аппарат для мастерских и строительных бригад, работающих с тяжёлыми металлическими профилями.",
    brand: "Aurora",
    model: "Stickmate 250",
    dailyPrice: 45,
    depositAmount: 205,
    quantityTotal: 2,
    baseQuantityAvailable: 2,
    power: 8.5,
    weight: 7.8,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.welding,
    specs: [
      { name: "Сварочный ток", value: "250", unit: "A" },
      { name: "Продолжительность включения", value: "60", unit: "%" },
      { name: "Диаметр электрода", value: "6", unit: "mm" },
      { name: "Область применения", value: "Тяжёлые металлические профили" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "stihl-ts-420",
    name: "Stihl TS 420 Cut-Off Saw",
    shortDescription: "Ручной резак по бетону и металлу для проемов, бордюров и труб.",
    description: "Высокомобильная отрезная пила для аварийных проемов, выравнивания дорожного покрытия, стальных профилей и коммунальных работ.",
    brand: "Stihl",
    model: "TS 420",
    dailyPrice: 58,
    depositAmount: 280,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 3.2,
    weight: 9.6,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: true,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Диаметр диска", value: "350", unit: "mm" },
      { name: "Глубина резания", value: "125", unit: "mm" },
      { name: "Тип двигателя", value: "Бензин" },
      { name: "Подключение воды", value: "Да" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "husqvarna-k770",
    name: "Husqvarna K 770 Cutter",
    shortDescription: "Универсальный дисковый резак для асфальта, бордюрного камня и армирующих работ.",
    description: "Надежная высокопроизводительная пила, используемая коммунальными службами, бригадами по укладке дорожного покрытия и генеральными подрядчиками при работе с плотными материалами.",
    brand: "Husqvarna",
    model: "K 770",
    dailyPrice: 62,
    depositAmount: 300,
    quantityTotal: 4,
    baseQuantityAvailable: 4,
    power: 3.7,
    weight: 10.1,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Диаметр диска", value: "350", unit: "mm" },
      { name: "Глубина резания", value: "125", unit: "mm" },
      { name: "Источник питания", value: "Бензин" },
      { name: "Вариант использования", value: "Бетон и сталь" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "makita-lc1230",
    name: "Makita LC1230 Metal Saw",
    shortDescription: "Пила по металлу холодной резки для профилей, швеллеров и изготовления площадок.",
    description: "Точная пила для резки металла для углов мастерских и мобильных производственных задач, где важна чистота кромок.",
    brand: "Makita",
    model: "LC1230",
    dailyPrice: 37,
    depositAmount: 170,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: 1.75,
    weight: 19.3,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Диаметр лезвия", value: "305", unit: "mm" },
      { name: "Тип резки", value: "Холодная нарезка" },
      { name: "Материал", value: "Металлические профили" },
      { name: "Источник питания", value: "220", unit: "V" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "eibenstock-ees-1400-3",
    name: "Eibenstock EES 1400-3 Wall Chaser",
    shortDescription: "Стенорез недоступен, пока заменяются защитные кожухи лезвий.",
    description: "Специализированный инструмент для чеканки в настоящее время нельзя арендовать до тех пор, пока не будут заменены защитное оборудование и пылезащитные уплотнения.",
    brand: "Eibenstock",
    model: "EES 1400-3",
    dailyPrice: 41,
    depositAmount: 190,
    quantityTotal: 2,
    baseQuantityAvailable: 0,
    power: 1.4,
    weight: 4.7,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Набор лезвий", value: "Двойной диск" },
      { name: "Ширина резки", value: "10-40", unit: "mm" },
      { name: "Примечание по ремонту", value: "Замена защиты лезвия" },
      { name: "Удаление пыли", value: "Поддерживается" },
    ],
  }),
  equipment({
    categorySlug: "saws-cutters",
    slug: "legacy-asphalt-saw-500",
    name: "Legacy Asphalt Saw 500",
    shortDescription: "Архивная дорожная пила сохранена только для ссылки на старый контракт.",
    description: "Запись об историческом оборудовании сохранена для отчетности и документации более ранних муниципальных проектов.",
    brand: "BuildRent Legacy",
    model: "Asphalt Saw 500",
    dailyPrice: 85,
    depositAmount: 430,
    quantityTotal: 1,
    baseQuantityAvailable: 0,
    power: 9,
    weight: 115,
    status: EquipmentStatus.ARCHIVED,
    isFeatured: false,
    imageUrls: imageLibrary.saws,
    specs: [
      { name: "Архивная заметка", value: "Только исторические записи" },
      { name: "Диаметр диска", value: "500", unit: "mm" },
      { name: "Тип двигателя", value: "Бензин" },
      { name: "Вариант использования", value: "Дорожный ремонт" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "bosch-gll-3-80-cg",
    name: "Bosch GLL 3-80 CG Laser Level",
    shortDescription: "Лазер зеленого луча для внутренней планировки и работ с подвесными потолками.",
    description: "Хорошо видимый лазерный уровень для обрамления перегородок, подвесных потолков, укладки плитки и выравнивания шкафов.",
    brand: "Bosch",
    model: "GLL 3-80 CG",
    dailyPrice: 24,
    depositAmount: 120,
    quantityTotal: 6,
    baseQuantityAvailable: 6,
    power: null,
    weight: 0.9,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Диапазон", value: "30", unit: "m" },
      { name: "Цвет луча", value: "Зеленый" },
      { name: "Точность", value: "+/- 0.2", unit: "mm/m" },
      { name: "Bluetooth", value: "Да" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "leica-rugby-620",
    name: "Leica Rugby 620 Rotary Laser",
    shortDescription: "Ротационный лазер для наружного применения для планировки, коммунальных услуг и выравнивания площадок.",
    description: "Роторный лазер профессионального уровня, используемый для обработки больших участков, фундаментов и выравнивания наружных коммуникаций.",
    brand: "Leica",
    model: "Rugby 620",
    dailyPrice: 48,
    depositAmount: 260,
    quantityTotal: 3,
    baseQuantityAvailable: 3,
    power: null,
    weight: 2.4,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Диапазон", value: "800", unit: "m" },
      { name: "Защита", value: "IP67" },
      { name: "Точность", value: "+/- 1.5", unit: "мм на 30 м" },
      { name: "Область применения", value: "Наружная сортировка" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "stanley-tlm330",
    name: "Stanley TLM330 Distance Meter",
    shortDescription: "Компактный лазерный измеритель для быстрого измерения помещений, фасадов и проемов.",
    description: "Удобный портативный дальномер для оценщиков отделки, поддержки обследований и планирования установки.",
    brand: "Stanley",
    model: "TLM330",
    dailyPrice: 12,
    depositAmount: 60,
    quantityTotal: 8,
    baseQuantityAvailable: 8,
    power: null,
    weight: 0.18,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Диапазон", value: "100", unit: "m" },
      { name: "Точность", value: "+/- 1.5", unit: "mm" },
      { name: "Отображать", value: "с подсветкой" },
      { name: "Функции", value: "Площадь и объем" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "ada-cube-360-home",
    name: "ADA Cube 360 Home Edition",
    shortDescription: "Лазерный уровень приостановлен из-за отклонения калибровки.",
    description: "Компактный лазерный уровень в настоящее время ожидает калибровки после того, как во время проверки качества был обнаружен дрейф.",
    brand: "ADA",
    model: "Cube 360 Home Edition",
    dailyPrice: 10,
    depositAmount: 45,
    quantityTotal: 5,
    baseQuantityAvailable: 0,
    power: null,
    weight: 0.35,
    status: EquipmentStatus.UNAVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Примечание по калибровке", value: "Ожидание калибровки" },
      { name: "Диапазон", value: "20", unit: "m" },
      { name: "Балочные плоскости", value: "1 х 360 градусов" },
      { name: "Резьба для штатива", value: "1/4" },
    ],
  }),
  equipment({
    categorySlug: "measuring-tools",
    slug: "trimble-m3-total-station",
    name: "Trimble M3 Total Station",
    shortDescription: "Станция геодезического класса для разметки местности, переноса осей и поддержки геодезии.",
    description: "Прецизионный инструмент для подрядчиков, которым требуется сложная передача геометрии и точный контроль объекта.",
    brand: "Trimble",
    model: "M3",
    dailyPrice: 120,
    depositAmount: 700,
    quantityTotal: 1,
    baseQuantityAvailable: 1,
    power: null,
    weight: 4.5,
    status: EquipmentStatus.AVAILABLE,
    isFeatured: false,
    imageUrls: imageLibrary.measuring,
    specs: [
      { name: "Угловая точность", value: "5", unit: "сек" },
      { name: "Диапазон с призмой", value: "3000", unit: "m" },
      { name: "Хранилище", value: "Внутренняя память" },
      { name: "Вариант использования", value: "План строительства" },
    ],
  }),
];
